use_frameworks!

target 'MyFirst_Example' do
  pod 'MyFirst', :path => '../'

  target 'MyFirst_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
